### ISSUE TITLE
Uncaught (in promise) TypeError: Object(...) is not a function at setup (vue-repl.js:16821:1)

### ISSUE THREAD

**Issue by Andy-xue** [vuejs/repl#222]
Hi! I can't seem to run vue-repl with vue-cli,, I get a browser console error

`
vue-repl.js:16821 Uncaught (in promise) TypeError: Object(...) is not a function
    at setup (vue-repl.js:16821:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6992:1)
    at setupStatefulComponent (runtime-core.esm-bundler.js:6608:1)
    at setupComponent (runtime-core.esm-bundler.js:6564:1)
    at mountComponent (runtime-core.esm-bundler.js:4423:1)
    at processComponent (runtime-core.esm-bundler.js:4398:1)
    at patch (runtime-core.esm-bundler.js:3993:1)
    at mountChildren (runtime-core.esm-bundler.js:4189:1)
    at mountElement (runtime-core.esm-bundler.js:4098:1)
    at processElement (runtime-core.esm-bundler.js:4070:1)
`

my dependencies:
`
"core-js": "^3.6.5",
   "@vue/repl": "4.1.1",
    "vue": "~3.2.0",
`

**Comment by sxzz** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by Andy-xue** [comment]
"core-js": "^3.8.3",
"vue": "~3.2.0",
"@vue/repl": "4.1.1"
按照上面的配置进行项目安装的时候会有问题，我想知道repl需要使用哪个版本的vue

**Comment by Andy-xue** [comment]
"core-js": "^3.8.3",
"vue": "-3.2.0",
"@vue/repl": "4.1.1"
There is a problem when installing the project according to the above configuration. I want to know which version of vue the repl needs to use.
